version: "3.7"

services:
  app:
    container_name: php-gacela.code-test
    image: tbc.code-test
    depends_on:
      - db
    volumes:
      - ./:/tbc/app
    working_dir: /tbc/app
    build:
      context: .
      dockerfile: .tcb/docker/app/Dockerfile
      target: dev
    ports:
      - "8085:8000"
    environment:
      DB_HOST: db
      DB_PASSWORD: root
    command: "php -S 0.0.0.0:8000 index.php"
